// Package development wires every brick into one place for IDE and REPL
// use. It is generated by goforge; do not edit by hand.
package development

import (
	_ "goforge.dev/gat/bases/cli"
	_ "goforge.dev/gat/components/assets"
	_ "goforge.dev/gat/components/config"
	_ "goforge.dev/gat/components/controller"
	_ "goforge.dev/gat/components/decorations"
	_ "goforge.dev/gat/components/gitdiff"
	_ "goforge.dev/gat/components/inputsrc"
	_ "goforge.dev/gat/components/linerange"
	_ "goforge.dev/gat/components/pager"
	_ "goforge.dev/gat/components/printer"
	_ "goforge.dev/gat/components/style"
	_ "goforge.dev/gat/components/termdetect"
)
